title: dddice
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: https://status.dddice.com
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: false
  useRelativeTime: true
  disableDarkMode: false
  shortDateFormat: 15:04 UTC — Jan 2
  down: "#e60000"
  systems:
    - name: Application
      category: Uncategorized
    - name: API
      category: Uncategorized
    - name: Blog
      category: Uncategorized
    - name: Cache
      category: Uncategorized
    - name: Database
      category: Uncategorized
    - name: Documentation
      category: Uncategorized
    - name: Status
      category: Uncategorized
      description: This site is hosted on Netlify and outside of our infrastructure
    - name: Worker
      category: Uncategorized
      description: Processes rolls, image processing, and other async jobs
    - name: WebSockets
      category: Uncategorized
  dateFormat: January 2, 2006 at 3:04 PM UTC
  brand: "#0a0c0f"
  enableLastMod: true
  headerTextColor: white
  logo: /img/logo.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: yearly
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - name: Uncategorized
      untitled: true
  description: We continuously monitor the status of our services and if there are
    any interruptions, a note will be posted here.
  enableCustomHTML: true
  useLargeHeaderDesign: false
